name: Build and Release

on: workflow_dispatch

jobs:
  unittest:
    uses: ./.github/workflows/unittest.yml

  build-and-release-test-pypi:
    runs-on: ubuntu-latest
    needs: unittest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U build
          pip install -U twine
      - name: Export Python path
        run:
          export PYTHONPATH=home/runner/work/config_loader_pkg/config_loader_pkg/:home/runner/work/config_loader_pkg/config_loader_pkg/pm_config_loader/
      - name: Build and Release
        run: |
          python -m build && python -m twine upload -r testpypi -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }} dist/*